openapi: 3.0.3
info:
  title: Plants Soil Lettuce (Webhook Engine)  - OpenAPI 3.0
  description: |-
    This is a Webhook Engine Core API based on the OpenAPI 3.0 specification.
    You can register as publisher and trigger (publish) events (message carried) as needed, all subscribers could receive the events instantly.
    You can register as subscriber with webhooks to listen on and receive events (messages carried) from publishers you subscribed.

    Some useful links:
    - [The Lettuce Webhook Engine repository](https://github.com/plants-soil/lettuce-webhook-hub)
  contact:
    email: danialdy@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://lettuce.plantssoil.com/api/v1
tags:
  - name: organization
    description: All APIs for organization registry
  - name: publisher
    description: All APIs for publisher registry
  - name: subscriber
    description: All APIs for subscriber registry
  - name: webhook
    description: All APIs for webhook registry
  - name: engine
    description: All APIs for webhook engine functions
paths:
  /organization:
    put:
      tags:
        - organization
      summary: Update an existing organization
      description: Update an existing organization by organizationId
      operationId: updateOrganization
      security:
        - api_key: []
        - webhook_auth:
            - write:organizations
            - read:organizations
    post:
      tags:
        - organization
      summary: Add a new organization
      description: Add a new organization
      operationId: addOrganization
      security:
        - api_key: []
        - webhook_auth:
            - write:organizations
            - read:organizations
  /organization/all:
    get:
      tags:
        - organization
      summary: Find all organizations with pagination
      description: Will find the organizations on the page specified (page, pageSize)
      operationId: findAllOrganizations
      security:
        - webhook_auth:
            - write:organizations
            - read:organizations
  /organization/{organizationId}:
    get:
      tags:
        - organization
      summary: Find organization by ID
      description: Returns a single organization
      operationId: findOrganizationById
      security:
        - webhook_auth:
            - write:organizations
            - read:organizations
    put:
      tags:
        - organization
      summary: Update an existing organization
      description: Update an existing organization by organizationId
      operationId: updateOrganizationById
      security:
        - api_key: []
        - webhook_auth:
            - write:organizations
            - read:organizations
  /publisher:
    post:
      tags:
        - publisher
      summary: Add a new publisher
      description: Add a new publisher
      operationId: addPublisher
      security:
        - api_key: []
        - webhook_auth:
            - write:publishers
            - read:publishers
  /publisher/all:
    get:
      tags:
        - publisher
      summary: Find all publishers with pagination
      description: Will find the publishers on the page specified (page, pageSize)
      operationId: findAllPublishers
      security:
        - webhook_auth:
            - write:publishers
            - read:publishers
  /publisher/{publisherId}:
    get:
      tags:
        - publisher
      summary: Find publisher by ID
      description: Returns a single publisher
      operationId: findPublisherById
      security:
        - webhook_auth:
            - write:publishers
            - read:publishers
    put:
      tags:
        - publisher
      summary: Update an existing publisher
      description: Update an existing publisher by publisherId
      operationId: updatePublisherById
      security:
        - api_key: []
        - webhook_auth:
            - write:publishers
            - read:publishers
  /publisher/{publisherId}/event:
    post:
      tags:
        - publisher
      summary: Add an event to an existing publisher
      description: add an event to an existing publisher by publisherId
      operationId: addEvent
      security:
        - api_key: []
        - webhook_auth:
            - write:events
            - read:events
  /publisher/{publisherId}/events:
    post:
      tags:
        - publisher
      summary: Add events to an existing publisher
      description: add events to an existing publisher by publisherId
      operationId: addEvents
      security:
        - api_key: []
        - webhook_auth:
            - write:events
            - read:events
  /publisher/{publisherId}/allEvents:
    get:
      tags:
        - publisher
      summary: Find all events which belong to the specific publisher
      description: Find all events which belong to the specific publisher with pagination
      operationId: findEvents
      security:
        - webhook_auth:
            - write:events
            - read:events
  /publisher/event/{eventId}:
    get:
      tags:
        - publisher
      summary: Find event by ID
      description: Returns a single event
      operationId: findEventById
      security:
        - api_key: []
        - webhook_auth:
            - write:events
            - read:events
  /publisher/{publisherId}/datagroup:
    post:
      tags:
        - publisher
      summary: Add a data group to an existing publisher
      description: add a data group to an existing publisher by publisherId
      operationId: addDataGroup
      security:
        - api_key: []
        - webhook_auth:
            - write:datagroups
            - read:datagroups
    get:
      tags:
        - publisher
      summary: Find data group which belong to the specific publisher
      description: Find data group which belong to the specific publisher with data group name
      operationId: findDataGroupByName
      security:
        - webhook_auth:
            - write:datagroups
            - read:datagroups
  /publisher/{publisherId}/datagroups:
    post:
      tags:
        - publisher
      summary: Add data groups to an existing publisher
      description: add data groups to an existing publisher by publisherId
      operationId: addDataGroups
      security:
        - api_key: []
        - webhook_auth:
            - write:datagroups
            - read:datagroups
  /publisher/{publisherId}/allDataGroups:
    get:
      tags:
        - publisher
      summary: Find all data groups which belong to the specific publisher
      description: Find all data groups which belong to the specific publisher with pagination
      operationId: findDataGroups
      security:
        - webhook_auth:
            - write:datagroups
            - read:datagroups
  /publisher/datagroup/{dataGroupId}:
    get:
      tags:
        - publisher
      summary: Find data group by ID
      description: Returns a single data group
      operationId: findDataGroupById
      security:
        - webhook_auth:
            - write:datagroups
            - read:datagroups
  /subscriber:
    post:
      tags:
        - subscriber
      summary: Add a new subscriber
      description: Add a new subscriber
      operationId: addSubscriber
      security:
        - api_key: []
        - webhook_auth:
            - write:subscribers
            - read:subscribers
  /subscriber/all:
    get:
      tags:
        - subscriber
      summary: Find all subscribers with pagination
      description: Will find the subscribers on the page specified (page, pageSize)
      operationId: findAllSubscribers
      security:
        - webhook_auth:
            - write:subscribers
            - read:subscribers
  /subscriber/{subscriberId}:
    get:
      tags:
        - subscriber
      summary: Find subscriber by ID
      description: Returns a single subscriber
      operationId: findSubscriberById
      security:
        - webhook_auth:
            - write:subscribers
            - read:subscribers
    put:
      tags:
        - subscriber
      summary: Update an existing subscriber
      description: Update an existing subscriber by subscriberId
      operationId: updateSubscriberById
      security:
        - api_key: []
        - webhook_auth:
            - write:subscribers
            - read:subscribers
    delete:
      tags:
        - subscriber
      summary: Deletes a subscriber
      description: delete a subscriber
      operationId: deleteSubscriber
      security:
        - api_key: []
        - webhook_auth:
            - write:subscribers
            - read:subscribers
  /webhook:
    post:
      tags:
        - webhook
      summary: Add a new webhook
      description: Add a new webhook
      operationId: addWebhook
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/all:
    get:
      tags:
        - webhook
      summary: Find all webhooks which belong to specific subscriber with pagination
      description: Will find the webhooks on the page specified (page, pageSize)
      operationId: findAllWebhooks
      security:
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/{webhookId}:
    get:
      tags:
        - webhook
      summary: Find webhook by ID
      description: Returns a single webhook
      operationId: findWebhookById
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
    put:
      tags:
        - webhook
      summary: Update an existing webhook
      description: Update an existing webhook by webhookId
      operationId: updateWebhookById
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/activate:
    post:
      tags:
        - webhook
      summary: Activate webhook
      description: Activate webhook and change webhook status to production
      operationId: activateWebhook
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/deactivate:
    post:
      tags:
        - webhook
      summary: Deactivate webhook
      description: Deactivate webhook and change webhook status to inactive
      operationId: deactivateWebhook
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/subscribeEvent:
    post:
      tags:
        - webhook
      summary: Subscribe a publisher event for webhook
      description: Subscribe a publisher event for webhook
      operationId: subscribeEvent
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/unsubscribeEvent:
    post:
      tags:
        - webhook
      summary: Unsubscribe a publisher event for webhook
      description: Unsubscribe a publisher event for webhook
      operationId: unsubscribeEvent
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/subscribeEvents:
    post:
      tags:
        - webhook
      summary: Subscribe publisher events for webhook
      description: Subscribe publisher events for webhook
      operationId: subscribeEvents
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/unsubscribeEvents:
    post:
      tags:
        - webhook
      summary: Unsubscribe publisher events for webhook
      description: Unsubscribe publisher events for webhook
      operationId: unsubscribeEvents
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/subscribeDataGroup:
    post:
      tags:
        - webhook
      summary: Subscribe a publisher data group for webhook
      description: Subscribe a publisher data group for webhook
      operationId: subscribeDataGroup
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/unsubscribeDataGroup:
    post:
      tags:
        - webhook
      summary: Unsubscribe a publisher data group for webhook
      description: Unsubscribe a publisher data group for webhook
      operationId: unsubscribeDataGroup
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/subscribeDataGroups:
    post:
      tags:
        - webhook
      summary: Subscribe publisher data groups for webhook
      description: Subscribe publisher data groups for webhook
      operationId: subscribeDataGroups
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/unsubscribeDataGroups:
    post:
      tags:
        - webhook
      summary: Unsubscribe publisher events for webhook
      description: Unsubscribe publisher events for webhook
      operationId: unsubscribeDataGroups
      security:
        - api_key: []
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/allSubscribedEvents:
    get:
      tags:
        - webhook
      summary: Find all subscribed events which belong to specific webhook with pagination
      description: Will find the subscribed events on the page specified (page, pageSize)
      operationId: findSubscribedEvents
      security:
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/allSubscribedDataGroups:
    get:
      tags:
        - webhook
      summary: Find all subscribed data groups which belong to specific webhook with pagination
      description: Will find the subscribed data groups on the page specified (page, pageSize)
      operationId: findSubscribedDataGroups
      security:
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /webhook/subscribedDataGroup:
    get:
      tags:
        - webhook
      summary: Find the subscribed data group which belong to specific webhook with data group name
      description: Will find the subscribed data group which belong to specific webhook with data group name
      operationId: findSubscribedDataGroup
      security:
        - webhook_auth:
            - write:webhooks
            - read:webhooks
  /engine/version:
    get:
      tags:
        - engine
      summary: Get the webhook engine version
      description: Get the webhook engine version
      operationId: getEngineVersion
      security:
        - webhook_auth:
            - write:engine
            - read:engine
  /engine/trigger:
    post:
      tags:
        - engine
      summary: Trigger a webhook event and post a message
      description: Trigger a webhook event and post a message
      operationId: trigger
      security:
        - api_key: []
        - webhook_auth:
            - write:engine
            - read:engine
components:
  securitySchemes:
    webhook_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://lettuce.plantssoil.com/oauth/authorize
          scopes:
            write:organizations: modify organizations in your account
            read:organizations: read your organizations
    api_key:
      type: apiKey
      name: api_key
      in: header